/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;

import javax.swing.JOptionPane;

import dao.ConexaoDB;
import model.Pessoa;
import model.TableModelPessoa;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.awt.event.ActionEvent;

/**
 *
 * @author User
 */
public class ViewTabelaPessoas extends javax.swing.JFrame {
    private TableModelPessoa tableModelPessoa;
    /**
     * Creates new form ViewTabelaPessoas
     */
    public ViewTabelaPessoas() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\User\\Downloads\\Guj-logo-1.png"));
    	setResizable(false);
    	setTitle("Estoque");
        initComponents();
        this.tableModelPessoa = new TableModelPessoa();
        this.jbTablePessoa.setModel(tableModelPessoa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jbTablePessoa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomePessoa = new javax.swing.JTextField();
        txtIdadePessoa = new javax.swing.JTextField();
        btnAdicionarPessoa = new javax.swing.JButton();
        btnRemoverPessoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbTablePessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jbTablePessoa);

        jLabel1.setText("Nome:");

        jLabel2.setText("Idade:");

        txtNomePessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePessoaActionPerformed(evt);
            }
        });

        btnAdicionarPessoa.setText("Adicionar");
        btnAdicionarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPessoaActionPerformed(evt);
            }
        });

        btnRemoverPessoa.setText("Remover");
        btnRemoverPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(15, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 375, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(jLabel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        						.addComponent(jLabel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(txtIdadePessoa, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(btnAdicionarPessoa)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(btnRemoverPessoa, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE))
        						.addComponent(txtNomePessoa, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))))
        			.addGap(19))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtNomePessoa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(24)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel2)
        					.addComponent(txtIdadePessoa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(btnAdicionarPessoa)
        					.addComponent(btnRemoverPessoa)))
        			.addPreferredGap(ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void btnAdicionarPessoaActionPerformed(java.awt.event.ActionEvent evt){                                                   
        String nome = this.txtNomePessoa.getText();
        int idade = Integer.parseInt(this.txtIdadePessoa.getText());
        
        Pessoa p = new Pessoa(nome, idade);
        try{
        ConexaoDB conexao = new ConexaoDB();
        conexao.executeConsulta("insert into pessoa(nome, idade) values ('_nome',_idade)".replace("_nome", nome).
        		replaceAll("_idade", String.valueOf(idade))); 
        } catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Erro ao inserir. ");
		}
        
        this.tableModelPessoa.addPessoa(p);
    }                                                  

    private void btnRemoverPessoaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int linhaSelecionada = this.jbTablePessoa.getSelectedRow();
        String nomeDeletar = String.valueOf(this.jbTablePessoa.getValueAt(jbTablePessoa.getSelectedRow(), 0));
        
        this.tableModelPessoa.removerPessoa(linhaSelecionada);
        
        try{
        	ConexaoDB conexao = new ConexaoDB();
        	int deletou = conexao.executeDelete("DELETE FROM PESSOA WHERE NOME = '_nomeDeletar'".replaceAll("_nomeDeletar", nomeDeletar));
        	if(deletou == 0){
        		JOptionPane.showMessageDialog(null, "Não foi possível deletar.");
        	}
        	
        } catch (Exception e) {
			// TODO: handle exception
		}
                
    }                                                

    private void txtNomePessoaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTabelaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTabelaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTabelaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTabelaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTabelaPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdicionarPessoa;
    private javax.swing.JButton btnRemoverPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jbTablePessoa;
    private javax.swing.JTextField txtIdadePessoa;
    private javax.swing.JTextField txtNomePessoa;
}
