/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;

import javax.swing.JOptionPane;

import dao.ConexaoDB;
import model.Pessoa;
import model.TableModelPessoa;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class ViewTabelaPessoas extends javax.swing.JFrame {
    private TableModelPessoa tableModelPessoa;
    
    /**
     * Creates new form ViewTabelaPessoas
     */
    public ViewTabelaPessoas() {
//    	setOpacity(0.0f);
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\User\\Downloads\\Guj-logo-1.png"));
    	setTitle("Estoque");
        initComponents();
        this.tableModelPessoa = new TableModelPessoa();
        this.jbTablePessoa.setModel(tableModelPessoa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jbTablePessoa = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtNomePessoa = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        btnAdicionarPessoa = new javax.swing.JButton();
        btnRemoverPessoa = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbTablePessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jbTablePessoa);

        lblNome.setText("Nome:");

        lblDescricao.setText("Descri\u00E7\u00E3o:");

        txtNomePessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePessoaActionPerformed(evt);
            }
        });

        btnAdicionarPessoa.setText("Adicionar");
        btnAdicionarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPessoaActionPerformed(evt);
            }
        });

        btnRemoverPessoa.setText("Remover");
        btnRemoverPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPessoaActionPerformed(evt);
            }
        });
        
        lblQuantidade = new JLabel("Quantidade:");
        
        txtQuantidade = new JTextField();
        txtQuantidade.setColumns(10);
        
        JLabel lblPreco = new JLabel("Preco:");
        
        txtPreco = new JTextField();
        txtPreco.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(15)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblPreco)
        					.addContainerGap())
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        							.addComponent(lblNome, GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        							.addComponent(lblDescricao, GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(btnAdicionarPessoa)
        								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(btnRemoverPessoa, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE))
        							.addComponent(txtNomePessoa, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
        							.addGroup(layout.createSequentialGroup()
        								.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        									.addComponent(txtPreco, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
        									.addComponent(txtDescricao, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        								.addGap(18)
        								.addComponent(lblQuantidade)
        								.addPreferredGap(ComponentPlacement.RELATED)
        								.addComponent(txtQuantidade)))
        						.addGap(98))
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 375, GroupLayout.PREFERRED_SIZE)
        						.addContainerGap(19, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNome)
        				.addComponent(txtNomePessoa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtDescricao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblDescricao)
        				.addComponent(lblQuantidade)
        				.addComponent(txtQuantidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblPreco)
        				.addComponent(txtPreco, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnAdicionarPessoa)
        				.addComponent(btnRemoverPessoa))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void btnAdicionarPessoaActionPerformed(java.awt.event.ActionEvent evt){                                                   
        String nome = this.txtNomePessoa.getText();
        String descricao = this.txtDescricao.getText();
        int quantidade = Integer.parseInt(this.txtQuantidade.getText());
        double preco = Double.parseDouble(this.txtPreco.getText());
        
        Pessoa p = new Pessoa(quantidade, nome, descricao, quantidade, preco);
        try{
        ConexaoDB conexao = new ConexaoDB();
        conexao.executeConsulta("insert into pessoa(nome, descricao, quantidade, preco) values ('_nome','_descricao',_quantidade,preco)".
        		replace("_nome", nome).
        		replace("_descricao", descricao).
        		replace("_quantidade", String.valueOf(quantidade)).
        		replace("_preco", String.valueOf(preco))); 
        } catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Erro ao inserir. ");
		}
        this.tableModelPessoa = new TableModelPessoa();
        this.jbTablePessoa.setModel(tableModelPessoa);
        
        //this.tableModelPessoa.refresh();
        
        //this.tableModelPessoa.addPessoa(p);
    }                                                  

    private void btnRemoverPessoaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int linhaSelecionada = this.jbTablePessoa.getSelectedRow();
        String nomeDeletar = String.valueOf(this.jbTablePessoa.getValueAt(jbTablePessoa.getSelectedRow(), 0));
        
        this.tableModelPessoa.removerPessoa(linhaSelecionada);
        
        try{
        	ConexaoDB conexao = new ConexaoDB();
        	int deletou = conexao.executeDelete("DELETE FROM PESSOA WHERE NOME = '_nomeDeletar'".replaceAll("_nomeDeletar", nomeDeletar));
        	if(deletou == 0){
        		JOptionPane.showMessageDialog(null, "Não foi possível deletar.");
        	}
        	
        } catch (Exception e) {
			// TODO: handle exception
		}
                
    }                                                

    private void txtNomePessoaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTabelaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTabelaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTabelaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTabelaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTabelaPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdicionarPessoa;
    private javax.swing.JButton btnRemoverPessoa;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jbTablePessoa;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNomePessoa;
    private JLabel lblQuantidade;
    private JTextField txtQuantidade;
    private JTextField txtPreco;
}
